### ISSUE TITLE
What's the right way to set MongoDB_URI ?

### ISSUE THREAD

**Issue by chafel** [jaysaurus/Co.Koa#2]
My `config/config.json` file looks like below: 
```
{
  "cors": {
    "allowMethods": "GET,HEAD,PUT,POST,DELETE,PATCH",
    "origin": "*",
    "exposeHeaders": "x-requested-with, Content-Type, origin, authorization, accept, content-type, x-experience-api-version, client-security-token",
    "maxAge": 3600,
    "credentials": true,
    "keepHeadersOnError": true
  },
  ...
  "welcomeMessage": false,
  "MongoDB_URI": "mongodb://localhost:27017/foo-bar"
}
```
But the db named with `foo-bar` does not work, the project still uses db `coKoa` in fact. This is not expected behavior. 

_I tried to set connectionString for `co-koa-mongoose-plugin` in `app/js` and it works! FYI_

**Comment by jaysaurus** [comment]
oh my goodness, I'm so sorry I don't know how I missed your comment. Did you solve this? I'll have a look tonight.

**Comment by jaysaurus** [comment]
Right, I suspect that you may have been working with an old version of Co.Koa.  I modularised Co.Koa's mongoose plugin in later releases.  therefore the correct way to set your connection string is in the config parameter of the plugin supplied to your project's app.js:

```javascript
const fs = require('fs');

if (fs.existsSync('./node_modules')) {
  const mongoosePlugin = require('co-koa-mongoose-plugin');
  const CoKoa = require('co-koa-core');
  try {
    // CONNECTION STRING IN THE OBJECT BELOW!
    // VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
    const coKoa = CoKoa(__dirname).launch(mongoosePlugin({
      connectionString: 'mongodb://localhost:27017/foo-bar'
    }));
    coKoa // koa-router is exposed below as "coKoa.router"
      .app
      .use(coKoa.router.routes())
      .use(coKoa.router.allowedMethods())
      .listen(coKoa.port);
  } catch (e) {
    console.error(
      e.message
        ? e.message
        : 'something unexpected brought the server down:');
  }
} else console.error('you must run "npm install" before running a new Co.Koa instance');
```
Can't apologise enough for slow response. It must have slipped through my emails/notifications.

happy coding!

**Comment by jaysaurus** [comment]
ah, saw your edit! Glad you got there :)

**Comment by chafel** [comment]
Thanks for your response anyway! 👍🏼
